### ISSUE TITLE
stk 0.7.3 does _not_ build with irrlicht 1.7.3

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#684]
**Author: vincent-c**

As per supertuxkart's [build instructions](http://supertuxkart.sourceforge.net/Build_STK_on_Linux#Installing_Irrlicht), I have tried building the latest stable release of supertuxkart (0.7.3) with the latest release of irrlicht (1.7.3), but the build is failing with the following errors below.

Reproducible with either cmake or autotools (autotools also complains about irrlicht being too old, which directly conflicts with the instructions given in stk's wiki).

Please note that my end-goal is to get stk 0.7.3 packaged for Debian and Ubuntu, so using an unreleased version of irrlicht isn't really an option.

1st error:

```
[ 37%] Building CXX object CMakeFiles/supertuxkart.dir/src/main_loop.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/main_loop.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/main_loop.cpp
In file included from /tmp/build/supertuxkart-0.7.3/src/main_loop.cpp:26:0:
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:154:5: error: 'ISceneNode' in namespace 'irr::scene' does not name a type
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:158:42: error: 'irr::scene::ISceneNode' has not been declared
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:161:51: error: 'irr::scene::ISceneNode' has not been declared
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:162:5: error: 'ISceneNode' in namespace 'irr::scene' does not name a type
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:168:5: error: 'ISceneNode' in namespace 'irr::scene' does not name a type
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:171:5: error: 'ISceneNode' in namespace 'irr::scene' does not name a type
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:172:45: error: 'irr::scene::ISceneNode' has not been declared
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.hpp:228:9: error: 'ISceneNode' in namespace 'irr::scene' does not name a type
make[*** [CMakeFiles/supertuxkart.dir/src/main_loop.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(fixed by adding "class ISceneNode;" in src/graphics/irr_driver.hpp, line 42)

Error 2:

```
[ 45%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.cpp
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.cpp: In member function 'void IrrDriver::initDevice()':
/tmp/build/supertuxkart-0.7.3/src/graphics/irr_driver.cpp:270:20: error: 'class irr::video::SMaterial' has no member named 'UseMipMaps'
make[*** [CMakeFiles/supertuxkart.dir/src/graphics/irr_driver.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(not sure how to fix, just commented out that line before continuing)

Error 3:

```
[ 38%] Building CXX object CMakeFiles/supertuxkart.dir/src/graphics/particle_emitter.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/graphics/particle_emitter.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/graphics/particle_emitter.cpp
/tmp/build/supertuxkart-0.7.3/src/graphics/particle_emitter.cpp: In member function 'void ParticleEmitter::clearParticles()':
/tmp/build/supertuxkart-0.7.3/src/graphics/particle_emitter.cpp:294:13: error: 'class irr::scene::IParticleSystemSceneNode' has no member named 'clearParticles'
make[*** [CMakeFiles/supertuxkart.dir/src/graphics/particle_emitter.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(again, commented out and continued with build...)

Error 4:

```
[ 43%] Building CXX object CMakeFiles/supertuxkart.dir/src/guiengine/skin.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/guiengine/skin.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/guiengine/skin.cpp
/tmp/build/supertuxkart-0.7.3/src/guiengine/skin.cpp: In member function 'void GUIEngine::Skin::drawRibbonChild(const recti&, GUIEngine::Widget*, bool, bool)':
/tmp/build/supertuxkart-0.7.3/src/guiengine/skin.cpp:856:24: error: 'class irr::video::SMaterial' has no member named 'UseMipMaps'
/tmp/build/supertuxkart-0.7.3/src/guiengine/skin.cpp:895:24: error: 'class irr::video::SMaterial' has no member named 'UseMipMaps'
make[*** [CMakeFiles/supertuxkart.dir/src/guiengine/skin.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(commented out)

Error 5:

```
[ 36%] Building CXX object CMakeFiles/supertuxkart.dir/src/guiengine/widgets/bubble_widget.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/guiengine/widgets/bubble_widget.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/bubble_widget.cpp
/tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/bubble_widget.cpp: In member function 'virtual void GUIEngine::BubbleWidget::add()':
/tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/bubble_widget.cpp:61:16: error: 'class irr::gui::IGUIStaticText' has no member named 'setTextRestrainedInside'
make[*** [CMakeFiles/supertuxkart.dir/src/guiengine/widgets/bubble_widget.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(commented out)

Error 6:

```
[ 37%] Building CXX object CMakeFiles/supertuxkart.dir/src/guiengine/widgets/CGUIEditBox.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/guiengine/widgets/CGUIEditBox.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/CGUIEditBox.cpp
/tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/CGUIEditBox.cpp: In member function 'virtual void CGUIEditBox::draw()':
/tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/CGUIEditBox.cpp:758:28: error: 'EGDC_GRAY_EDITABLE' was not declared in this scope
/tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/CGUIEditBox.cpp:760:18: error: 'EGDC_FOCUSED_EDITABLE' was not declared in this scope
/tmp/build/supertuxkart-0.7.3/src/guiengine/widgets/CGUIEditBox.cpp:760:42: error: 'EGDC_EDITABLE' was not declared in this scope
make[*** [CMakeFiles/supertuxkart.dir/src/guiengine/widgets/CGUIEditBox.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(commented out)

Error 7:

```
[ 61%] Building CXX object CMakeFiles/supertuxkart.dir/src/states_screens/dialogs/add_device_dialog.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/states_screens/dialogs/add_device_dialog.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/states_screens/dialogs/add_device_dialog.cpp
/tmp/build/supertuxkart-0.7.3/src/states_screens/dialogs/add_device_dialog.cpp: In constructor 'AddDeviceDialog::AddDeviceDialog()':
/tmp/build/supertuxkart-0.7.3/src/states_screens/dialogs/add_device_dialog.cpp:68:8: error: 'class irr::gui::IGUIStaticText' has no member named 'setRightToLeft'
make[*** [CMakeFiles/supertuxkart.dir/src/states_screens/dialogs/add_device_dialog.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(commented out)

Error 8:

```
[ 39%] Building CXX object CMakeFiles/supertuxkart.dir/src/states_screens/dialogs/track_info_dialog.cpp.o
/usr/bin/c++   -DHAVE_OGGVORBIS -DNDEBUG -DSUPERTUXKART_DATADIR=\"/usr/share/games/supertuxkart\" -DENABLE_BIDI=1 -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -I/tmp/build/supertuxkart-0.7.3/src -I/tmp/build/supertuxkart-0.7.3/src/enet/include -I/tmp/build/supertuxkart-0.7.3/src/bullet/src -I/usr/include/AL -I/usr/include/irrlicht    -Wall -O2 -o CMakeFiles/supertuxkart.dir/src/states_screens/dialogs/track_info_dialog.cpp.o -c /tmp/build/supertuxkart-0.7.3/src/states_screens/dialogs/track_info_dialog.cpp
/tmp/build/supertuxkart-0.7.3/src/states_screens/dialogs/track_info_dialog.cpp: In member function 'void TrackInfoDialog::addHighScoreWidgets(int, int)':
/tmp/build/supertuxkart-0.7.3/src/states_screens/dialogs/track_info_dialog.cpp:202:21: error: 'class irr::gui::IGUIStaticText' has no member named 'setTextRestrainedInside'
make[*** [CMakeFiles/supertuxkart.dir/src/states_screens/dialogs/track_info_dialog.cpp.o](3]:) Error 1
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[2](3]:): *** [Error 2
make[2](CMakeFiles/supertuxkart.dir/all]): Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
make[*** [all](1]:) Error 2
make[Leaving directory `/tmp/build/supertuxkart-0.7.3/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
make: *** [build](1]:) Error 2
```

(commented out)

```
[100%] Built target supertuxkart
```

I have no experience whatsoever with irrlicht, so I don't know whether it's worth the effort to fix stk 0.7.3 to build with irrlicht 1.7.3. However, if necessary, I'd accept small patches to irrlicht 1.7.3 in order to get stk working.
