### ISSUE TITLE
Patch to build with Irrlicht 1.8.0 svn revision 3993

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#556]
**Author: winterheart**

When I trying build stk, I get this error

```
make[2]: Entering directory `/opt/supertuxkart/stk/src'
g++ -DPACKAGE_NAME=\"supertuxkart\" -DPACKAGE_TARNAME=\"supertuxkart\" -DPACKAGE_VERSION=\"SVN\" -DPACKAGE_STRING=\"supertuxkart\ SVN\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"supertuxkart\" -DVERSION=\"SVN\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_AL_AL_H=1 -DHAVE_OGGVORBIS=1 -DENABLE_BIDI=1 -DSVNVERSION=\"10121\" -DBT_NO_PROFILE=/\*\*/ -DHAS_GETHOSTBYADDR_R=1 -DHAS_GETHOSTBYNAME_R=1 -DHAS_POLL=1 -DHAS_FCNTL=1 -DHAS_INET_PTON=1 -DHAS_INET_NTOP=1 -DHAS_MSGHDR_FLAGS=1 -DHAS_SOCKLEN_T=1 -I.  -DSUPERTUXKART_DATADIR="\"/usr/local/share/games/supertuxkart/\"" -I./bullet/src/ -I./enet/include/ -I/usr/local/include -I /opt/supertuxkart/irrlicht/include -I /opt/supertuxkart/irrlicht/include/irrlicht -I/usr/local/include  -Wall -DNDEBUG -O2 -MT CGUIEditBox.o -MD -MP -MF .deps/CGUIEditBox.Tpo -c -o CGUIEditBox.o `test -f 'guiengine/widgets/CGUIEditBox.cpp' || echo './'`guiengine/widgets/CGUIEditBox.cpp
In file included from guiengine/widgets/CGUIEditBox.cpp:5:0:
guiengine/widgets/CGUIEditBox.h:39:33: error: conflicting return type specified for virtual const irr::video::SColor& CGUIEditBox::getOverrideColor() const
/opt/supertuxkart/irrlicht/include/IGUIEditBox.h:51:25: error:   overriding virtual irr::video::SColor irr::gui::IGUIEditBox::getOverrideColor() const
```

In attached file patch which fix this error.
