### ISSUE TITLE
"install new driver" on Ubuntu 14.04

### ISSUE THREAD

**Issue by stiebel** [supertuxkart/stk-code#2223]
Hi,
I just downloaded stk 0.9 and it works fine with my ubuntu 14.04 with Intel® Core™ i7-4770K.

But on every start I get the message "install new graphics driver" which i cannot dow, because the intel-linux driver installer does not support 14.04 anymore.

No big issue, because everything works fine, but worth a thought.

Roland

**Comment by stiebel** [comment]
the original German message is:
Dein Treiber ist zu alt, Bitte installiere die neuste Version des Grafiktreibers

**Comment by stiebel** [comment]
the terminal output is:

Adding language fallback de
Irrlicht Engine version 1.8.0
Linux 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64
[warn   ] [IrrDriver Temp Logger]: Level 2: X Error: GLXBadFBConfig

[warn   ] [IrrDriver Temp Logger]: Level 2: From call : unknown

[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Vertex shader compilation failed at position -1:


[warn   ] [IrrDriver Temp Logger]: Level 3: Pixel shader compilation failed at position -1:


[info   ] IrrDriver: OpenGL version: 3.3
[info   ] IrrDriver: OpenGL vendor: Intel Open Source Technology Center
[info   ] IrrDriver: OpenGL renderer: Mesa DRI Intel(R) Haswell Desktop 
[info   ] IrrDriver: OpenGL version string: 3.3 (Core Profile) Mesa 10.1.3
[info   ] GLDriver: AMD Vertex Shader Layer Present
[info   ] GLDriver: ARB Base Instance Present
[info   ] GLDriver: ARB Texture Storage Present
[info   ] GLDriver: ARB Shader Atomic Counters Present
[info   ] GLDriver: ARB Uniform Buffer Object Present
[info   ] irr_driver: GLSL supported.
[info   ] GUIEngine: scale: 2.269504
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.frag
[info   ] GLWrap: Compiling shader : data/shaders/texturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/uniformcolortexturedquad.frag
[info   ] GrandPrixManager: Loading Grand Prix files from data/grandprix/
[info   ] GrandPrixManager: Loading Grand Prix files from /home/roland/.local/share/supertuxkart/grandprix/
[info   ] ClientNetworkManager: Host initialized.
[info   ] ClientNetworkManager: Ready !
[warn   ] OpenGL: Driver is too old!
[info   ] GLWrap: Compiling shader : data/shaders/coloredquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/coloredquad.frag
[info   ] GLWrap: Compiling shader : data/shaders/colortexturedquad.vert
[info   ] GLWrap: Compiling shader : data/shaders/colortexturedquad.frag
[info   ] STKHost: Listening has been stopped

**Comment by deveee** [comment]
If you don't care about stability, you can use oibaf ppa:
https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
or just compile newer mesa driver yourself.

You can also disable this popup message in config.xml file:
$HOME/.config/supertuxkart/0.8.2/config.xml
You must change old_driver_popup to false.

But I remember that there were some issues on Ubuntu 14.04, at least with Intel HD 3000/4000. But you have newer graphics card, maybe it works fine for you.

Anyway this message should be displayed for mesa version older than 10.3 because older versions were causing some glitches/crashes. For example something like this: https://github.com/supertuxkart/stk-code/issues/1564 :)
