### ISSUE TITLE
SuperTuxKart fails to build with bullet 2.81

### ISSUE THREAD

**Issue by supertuxkart-sourceforge-migration** [supertuxkart/stk-code#1125]
**Author: gallaecio**

```
/chakra/games/supertuxkart/src/SuperTuxKart-0.8/src/physics/btKartRaycast.cpp:66:72: error: invalid conversion from 'const btRigidBody*' to 'btRigidBody*' [-fpermissive]
   btRigidBody* body = btRigidBody::upcast(rayCallback.m_collisionObject);
```

Migrated-From: https://sourceforge.net/apps/trac/supertuxkart/ticket/1069
