### ISSUE TITLE
Build failure with SDL 2.0.14

### ISSUE THREAD

**Issue by reinerh** [supertuxkart/stk-code#4467]
STK fails to build with SDL 2.0.14.

```
src/input/gamepad_config.cpp:35:45: error: static assertion failed: non continous name
   35 | static_assert(SDL_CONTROLLER_BUTTON_MAX - 1 == SDL_CONTROLLER_BUTTON_DPAD_RIGHT, "non continous name");
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The `static_assert` checks that the last element of the `SDL_GameControllerButton` enum is `SDL_CONTROLLER_BUTTON_DPAD_RIGHT`, but the new SDL version contains new elements.
The enum is now ending with `SDL_CONTROLLER_BUTTON_TOUCHPAD`.
