### ISSUE TITLE
Cannot run game with hardware skinning

### ISSUE THREAD

**Issue by deveee** [supertuxkart/stk-code#2961]
Happens on intel HD4000 in current git. It shows unrecognized identifier 'binding' when compiling shaders:
```
[error  ] ShaderFilesManager: Error in shader object_pass.vert
[error  ] ShaderFilesManager: 0:78(17): error: unrecognized layout identifier `binding'
```

And btw. when I added graphical restriction and then run advanced pipeline in multiplayer it looks wrong too:
![zrzut ekranu z 2017-10-21 08-40-28](https://user-images.githubusercontent.com/5108558/31849006-b36cd84a-b63b-11e7-9f1f-76e676586070.png)

**Comment by Benau** [comment]
Can you try again?

I tested on hd3000, amd 5670, nv GT 240 all working fine

Seems the ubo has to be subdata in old way(or I need to create the fence later after postprocessing)

**Comment by Benau** [comment]
btw can you reproduce colorization mask failed if you enable texture compression in your intel in linux?
![icy_soccer_field-2017 10 22_02 53 57](https://user-images.githubusercontent.com/3252341/31855001-6b4b0d54-b6d4-11e7-8d08-a8f77a87ae74.png)

**Comment by deveee** [comment]
It's much better, but still not 100% correct. These two issues (multiplayer view and shaders compilation error) are fixed, but nvidia driver is still not happy:
https://youtu.be/np49kRdlkPQ
There is also some flickering in game (looks like some triangles are white).

I checked 63ecbefbdd52744d0d5f1a47e7473d53e1afad97 and it was working. I can git bisect if you want.

And I was able to reproduce the colorization mask issue on both intel and nvidia when texture compression is enabled. But then I removed texture cache and now it seems to work fine.

**Comment by deveee** [comment]
Git bisect showed 0d96906d54c173f3d7ab8c8e2e5b7ca685b5c776

**Comment by deveee** [comment]
It seems that it's the same reason that you disabled if (Weight[i] < 0.01) in recent commit... I have to totally remove if (Weight[0] < 0.01), otherwise it flickers.

**Comment by deveee** [comment]
This works for me:
```
diff --git a/data/shaders/instanced_skinning.vert b/data/shaders/instanced_skinning.vert
index 1ab64ddfe6..385f3add48 100644
--- a/data/shaders/instanced_skinning.vert
+++ b/data/shaders/instanced_skinning.vert
@@ -63,6 +63,27 @@ void main(void)
     vec4 skinned_normal = vec4(0.);
     vec4 skinned_tangent = vec4(0.);
     vec4 skinned_bitangent = vec4(0.);
+
+    for (int i = 0; i < 4; i++)
+    {
+        // Logically we should break if the weight is (almost) zero
+        // given the fact that it's sorted from high to low,
+        // but GT240 will cause glitches
+        //if (Weight[i] < 0.01)
+        //{
+        //    break;
+        //}
+        mat4 joint_matrix = mat4(
+            texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4),
+            texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4 + 1),
+            texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4 + 2),
+            texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4 + 3));
+        skinned_position += Weight[i] * joint_matrix * idle_position;
+        skinned_normal += Weight[i] * joint_matrix * idle_normal;
+        skinned_tangent += Weight[i] * joint_matrix * idle_tangent;
+        skinned_bitangent += Weight[i] * joint_matrix * idle_bitangent;
+    }
+
     if (Weight[0] < 0.01)
     {
         skinned_position = idle_position;
@@ -70,28 +91,6 @@ void main(void)
         skinned_tangent = idle_tangent;
         skinned_bitangent = idle_bitangent;
     }
-    else
-    {
-        for (int i = 0; i < 4; i++)
-        {
-            // Logically we should break if the weight is (almost) zero
-            // given the fact that it's sorted from high to low,
-            // but GT240 will cause glitches
-            //if (Weight[i] < 0.01)
-            //{
-            //    break;
-            //}
-            mat4 joint_matrix = mat4(
-                texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4),
-                texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4 + 1),
-                texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4 + 2),
-                texelFetch(skinning_tex, (Joint[i] + skinning_offset) * 4 + 3));
-            skinned_position += Weight[i] * joint_matrix * idle_position;
-            skinned_normal += Weight[i] * joint_matrix * idle_normal;
-            skinned_tangent += Weight[i] * joint_matrix * idle_tangent;
-            skinned_bitangent += Weight[i] * joint_matrix * idle_bitangent;
-        }
-    }
 
     gl_Position = ProjectionViewMatrix *  ModelMatrix * skinned_position;
     // Keep orthogonality
```

And it looks that access to textures inside a branch that depends on input value is not legal. Or is legal only for uniforms.

**Comment by Benau** [comment]
Seem that I have to use the old tricks in ubo skinning than writing easy-understand shader... can you retry?

**Comment by deveee** [comment]
It works fine now, thanks!
